### ISSUE TITLE
Arrumar solução alternativa para o .group_by

### ISSUE THREAD

**Issue by matheusherique** [MatheusRich/SIGS-GCES#25]
## Descrição do Problema
Por erros de banco de dados, o agrupamento não estava sendo possível visualizar a página de solicitações, mas a remoção do mesmo gerou um ambiguidade na coleta de dados, fazendo com que o mesmo dado fosse repetido várias vezes.

## Comportamento Esperado
Um dado deve ser mostrado apenas uma vez.

## Comportamento Atual 
O mesmo dado está sendo repetido pelo menos quatro vezes.

## Passos Para Reproduzir o Problema

  1.Devem existir solicitações de alocação pendentes.
  2.Acessar a página de solicitações pendentes.

**Comment by MatheusRich** [comment]
Verifiquem se [essas linhas removidas](https://github.com/MatheusRich/SIGS-GCES/commit/14511c22c2c8b875881e8bc01dc92faa097cb7c2#diff-038ce6c1b8f7b22ab65741df0ebe9c3e) não fazem diferença. Provavelmente essas linhas aqui faziam algum tipo de validação antes de exibir os elementos:

```ruby
<% unless room.nil? %>	
  <% next unless @department_rooms.include? room %>
<% end %>
```
