### ISSUE TITLE
Adicionar ícones

### ISSUE THREAD

**Issue by MatheusRich** [MatheusRich/SIGS-GCES#35]
## Descrição do Problema
No sistema não há muitos ícones, e os que estão presentes são imagens .png.

## Comportamento Esperado
Deve existir uma biblioteca de ícones para o projeto (Font Awesome) 

## Comportamento Atual 
Os ícones são imagens .png

**Comment by MatheusRich** [comment]
Aparente já há uma biblioteca de ícones em uso (https://getbootstrap.com/docs/3.3/components/), então não é necessário incluir o FontAwesome

**Comment by matheusherique** [comment]
Nós vimos isso. Mas vamos refatorar os ícones.
